name: Build and Run Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t dot_env .
      
    - name: Run Docker Image
      run: |
        docker run dot_env

