name: Docker Hub Workflow

on: [push]
env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/$DOCKER_IMAGE_NAME .

      - name: List local docker images
        run: docker image ls

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${{ env.DOCKER_IMAGE_NAME }}


  test-image-locally:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: |
          echo "KEY=I'm Going Slightly Mad" > .env
      
      - name: Pull Docker image
        run: docker pull uxjp/dot_env
      
      - name: Run Docker container
        run: docker run -v "$(pwd)/.env:/.env" uxjp/dot_env
