name: Docker Hub Workflow

on: [push]
env:
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ghcr.io/$DOCKER_IMAGE_NAME .

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${{ env.DOCKER_IMAGE_NAME }}


  test-image-locally:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: |
          echo "KEY=I'm Going Slightly Mad" > .env
      
      - name: Pull Docker image
        run: docker pull uxjp/dot_env
      
      - name: Run Docker container
        run: docker run -v "$(pwd)/.env:/.env" uxjp/dot_env
